name: flutter_social_keyboard
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/saytoonz/flutter_social_keyboard

environment:
  sdk: '>=2.19.0-127.0.dev <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  emoji_picker_flutter: ^1.3.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # plugin:
  #   platforms:
  #     # some_platform:
  #     #   pluginClass: somePluginClass
  
  assets:
    - packages/flutter_social_keyboard/icons/icons8-emoji-96.png
    - packages/flutter_social_keyboard/icons/icons8-gif-96.png
    - packages/flutter_social_keyboard/icons/icons8-sticker-100.png
