name: flutter_social_keyboard
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/saytoonz/flutter_social_keyboard

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  emoji_picker_flutter: ^1.3.1
  http: ^0.13.5
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # plugin:
  #   platforms:
  #     # some_platform:
  #     #   pluginClass: somePluginClass
  
  assets:
    - packages/flutter_social_keyboard/icons/emoji.png
    - packages/flutter_social_keyboard/icons/gif.png
    - packages/flutter_social_keyboard/icons/sticker.png
